/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AccountAttributeResponseJson
 */
export interface AccountAttributeResponseJson {

    /**
     * @type {string}
     * @memberof AccountAttributeResponseJson
     * @example OVERDRAFT_START_DATE
     */
    name: string;

    /**
     * @type {string}
     * @memberof AccountAttributeResponseJson
     * @example 613c83ea-80f9-4560-8404-b9cd4ec42a7f
     */
    account_attribute_id: string;

    /**
     * @type {string}
     * @memberof AccountAttributeResponseJson
     * @example 1234BW
     */
    product_code: string;

    /**
     * @type {string}
     * @memberof AccountAttributeResponseJson
     * @example DATE_WITH_DAY
     */
    type: string;

    /**
     * @type {string}
     * @memberof AccountAttributeResponseJson
     * @example LKJL98769F
     */
    product_instance_code?: string;

    /**
     * @type {string}
     * @memberof AccountAttributeResponseJson
     * @example 2012-04-23
     */
    value: string;
}
