/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ViewJSONV121 } from './view-jsonv121';
 /**
 * 
 *
 * @export
 * @interface AccountJSON
 */
export interface AccountJSON {

    /**
     * @type {string}
     * @memberof AccountJSON
     * @example 123
     */
    id: string;

    /**
     * @type {string}
     * @memberof AccountJSON
     * @example OBP
     */
    label: string;

    /**
     * @type {Array<ViewJSONV121>}
     * @memberof AccountJSON
     */
    views_available: Array<ViewJSONV121>;

    /**
     * @type {string}
     * @memberof AccountJSON
     * @example gh.29.uk
     */
    bank_id: string;
}
