/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountRoutingJsonV121 } from './account-routing-json-v121';
 /**
 * 
 *
 * @export
 * @interface AccountHeldJson
 */
export interface AccountHeldJson {

    /**
     * @type {string}
     * @memberof AccountHeldJson
     * @example 123
     */
    number: string;

    /**
     * @type {Array<AccountRoutingJsonV121>}
     * @memberof AccountHeldJson
     */
    account_routings: Array<AccountRoutingJsonV121>;

    /**
     * @type {string}
     * @memberof AccountHeldJson
     * @example My Account
     */
    label: string;

    /**
     * @type {string}
     * @memberof AccountHeldJson
     * @example 123
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof AccountHeldJson
     * @example 7b97bd26-583b-4c3b-8282-55ea9d934aad
     */
    id: string;
}
