/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountRoutingJsonV121 } from './account-routing-json-v121';
 /**
 * 
 *
 * @export
 * @interface AccountAccessV500
 */
export interface AccountAccessV500 {

    /**
     * @type {AccountRoutingJsonV121}
     * @memberof AccountAccessV500
     */
    account_routing: AccountRoutingJsonV121;

    /**
     * @type {string}
     * @memberof AccountAccessV500
     * @example owner
     */
    view_id: string;
}
