/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue } from './obpv210banks-bankidaccounts-accountidviewidtransactionrequesttypes-sandboxtantransactionrequests-value';
import { Obpv400banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesAGENTCASHWITHDRAWALtransactionrequestsTo } from './obpv400banks-bankidaccounts-accountidviewidtransactionrequesttypes-agentcashwithdrawaltransactionrequests-to';
 /**
 * 
 *
 * @export
 * @interface AGENTCASHWITHDRAWALTransactionrequestsBody
 */
export interface AGENTCASHWITHDRAWALTransactionrequestsBody {

    /**
     * @type {Obpv400banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesAGENTCASHWITHDRAWALtransactionrequestsTo}
     * @memberof AGENTCASHWITHDRAWALTransactionrequestsBody
     */
    to: Obpv400banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesAGENTCASHWITHDRAWALtransactionrequestsTo;

    /**
     * @type {Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue}
     * @memberof AGENTCASHWITHDRAWALTransactionrequestsBody
     */
    value: Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue;

    /**
     * @type {string}
     * @memberof AGENTCASHWITHDRAWALTransactionrequestsBody
     * @example Description of the object. Maximum length is 2000. It can be any characters here.
     */
    description: string;

    /**
     * @type {string}
     * @memberof AGENTCASHWITHDRAWALTransactionrequestsBody
     * @example SHARED
     */
    charge_policy: string;

    /**
     * @type {string}
     * @memberof AGENTCASHWITHDRAWALTransactionrequestsBody
     * @example 20200127
     */
    future_date: string;
}
