/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AtmSupportedCurrenciesJson
 */
export interface AtmSupportedCurrenciesJson {

    /**
     * @type {string}
     * @memberof AtmSupportedCurrenciesJson
     * @example atme-9a0f-4bfa-b30b-9003aa467f51
     */
    atm_id: string;

    /**
     * @type {Array<string>}
     * @memberof AtmSupportedCurrenciesJson
     */
    supported_currencies: Array<string>;
}
