/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddressJsonV300 } from './address-json-v300';
import { BranchRoutingJsonV141 } from './branch-routing-json-v141';
import { DriveUpJsonV330 } from './drive-up-json-v330';
import { LobbyJsonV330 } from './lobby-json-v330';
import { LocationJsonV140 } from './location-json-v140';
import { MetaJsonV140 } from './meta-json-v140';
 /**
 * 
 *
 * @export
 * @interface BranchJsonV300
 */
export interface BranchJsonV300 {

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example Branch by the Lake
     */
    name: string;

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example +381631954907
     */
    phone_number: string;

    /**
     * @type {LocationJsonV140}
     * @memberof BranchJsonV300
     */
    location: LocationJsonV140;

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example Full service store
     */
    branch_type: string;

    /**
     * @type {BranchRoutingJsonV141}
     * @memberof BranchJsonV300
     */
    branch_routing: BranchRoutingJsonV141;

    /**
     * @type {DriveUpJsonV330}
     * @memberof BranchJsonV300
     */
    drive_up: DriveUpJsonV330;

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example short walk to the lake from here
     */
    more_info: string;

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example bank-id-123
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example branch-id-123
     */
    id: string;

    /**
     * @type {MetaJsonV140}
     * @memberof BranchJsonV300
     */
    meta: MetaJsonV140;

    /**
     * @type {LobbyJsonV330}
     * @memberof BranchJsonV300
     */
    lobby: LobbyJsonV330;

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example wheelchair, atm usuable by the visually impaired
     */
    accessibleFeatures: string;

    /**
     * @type {AddressJsonV300}
     * @memberof BranchJsonV300
     */
    address: AddressJsonV300;

    /**
     * @type {string}
     * @memberof BranchJsonV300
     * @example true
     */
    is_accessible: string;
}
