/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConnectorMetricJson
 */
export interface ConnectorMetricJson {

    /**
     * @type {string}
     * @memberof ConnectorMetricJson
     * @example mapper
     */
    connector_name: string;

    /**
     * @type {number}
     * @memberof ConnectorMetricJson
     * @example 1000
     */
    duration: number;

    /**
     * @type {string}
     * @memberof ConnectorMetricJson
     * @example getBanks
     */
    function_name: string;

    /**
     * @type {string}
     * @memberof ConnectorMetricJson
     * @example 12345
     */
    correlation_id: string;

    /**
     * @type {string}
     * @memberof ConnectorMetricJson
     */
    date: string;
}
