/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConsentAccessAccountsJson
 */
export interface ConsentAccessAccountsJson {

    /**
     * @type {string}
     * @memberof ConsentAccessAccountsJson
     */
    msisdn?: string;

    /**
     * @type {string}
     * @memberof ConsentAccessAccountsJson
     */
    maskedPan?: string;

    /**
     * @type {string}
     * @memberof ConsentAccessAccountsJson
     */
    currency?: string;

    /**
     * @type {string}
     * @memberof ConsentAccessAccountsJson
     */
    pan?: string;

    /**
     * @type {string}
     * @memberof ConsentAccessAccountsJson
     * @example RS35260005601001611379
     */
    iban?: string;

    /**
     * @type {string}
     * @memberof ConsentAccessAccountsJson
     */
    bban?: string;
}
