/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ContractJsonV500
 */
export interface ContractJsonV500 {

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    form_of_payment?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    maturity_date?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    renewal_date?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    interest_rate?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    instrument_status_code?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    product_description?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    issuance_amount?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    term?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    is_substituted?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    opening_date?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     * @example cache
     */
    payment_method?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     * @example 787LOW
     */
    product_code: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    branch_code?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     * @example LKJL98769F
     */
    contract_code: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    instrument_status_definition?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    cancellation_date?: string;

    /**
     * @type {string}
     * @memberof ContractJsonV500
     */
    interest_amount?: string;
}
