/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CounterpartyJson400 } from './counterparty-json400';
 /**
 * 
 *
 * @export
 * @interface CounterpartiesJson400
 */
export interface CounterpartiesJson400 {

    /**
     * @type {Array<CounterpartyJson400>}
     * @memberof CounterpartiesJson400
     */
    counterparties: Array<CounterpartyJson400>;
}
