/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomerJsonV310 } from './customer-json-v310';
import { UserWithAttributesResponseJson } from './user-with-attributes-response-json';
 /**
 * 
 *
 * @export
 * @interface CustomerAndUsersWithAttributesResponseJson
 */
export interface CustomerAndUsersWithAttributesResponseJson {

    /**
     * @type {CustomerJsonV310}
     * @memberof CustomerAndUsersWithAttributesResponseJson
     */
    customer: CustomerJsonV310;

    /**
     * @type {Array<UserWithAttributesResponseJson>}
     * @memberof CustomerAndUsersWithAttributesResponseJson
     */
    users: Array<UserWithAttributesResponseJson>;
}
