/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AmountOfMoneyJsonV121 } from './amount-of-money-json-v121';
import { CustomerAttributeResponseJsonV300 } from './customer-attribute-response-json-v300';
import { CustomerCreditRatingJSON } from './customer-credit-rating-json';
import { CustomerFaceImageJson } from './customer-face-image-json';
 /**
 * 
 *
 * @export
 * @interface CustomerWithAttributesJsonV310
 */
export interface CustomerWithAttributesJsonV310 {

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh
     */
    customer_id: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example Sr
     */
    name_suffix: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example felixsmith@example.com
     */
    email: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example DERBY6
     */
    branch_id: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example +44 07972 444 876
     */
    mobile_phone_number: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example 5987953
     */
    customer_number: string;

    /**
     * @type {Array<CustomerAttributeResponseJsonV300>}
     * @memberof CustomerWithAttributesJsonV310
     */
    customer_attributes: Array<CustomerAttributeResponseJsonV300>;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example Master
     */
    highest_education_attained: string;

    /**
     * @type {Array<string>}
     * @memberof CustomerWithAttributesJsonV310
     */
    dob_of_dependants: Array<string>;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     */
    date_of_birth: string;

    /**
     * @type {CustomerCreditRatingJSON}
     * @memberof CustomerWithAttributesJsonV310
     */
    credit_rating?: CustomerCreditRatingJSON;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     */
    last_ok_date: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example worker
     */
    employment_status: string;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example Eveline Tripman
     */
    legal_name: string;

    /**
     * @type {AmountOfMoneyJsonV121}
     * @memberof CustomerWithAttributesJsonV310
     */
    credit_limit?: AmountOfMoneyJsonV121;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example Dr.
     */
    title: string;

    /**
     * @type {CustomerFaceImageJson}
     * @memberof CustomerWithAttributesJsonV310
     */
    face_image: CustomerFaceImageJson;

    /**
     * @type {number}
     * @memberof CustomerWithAttributesJsonV310
     * @example 1
     */
    dependants: number;

    /**
     * @type {string}
     * @memberof CustomerWithAttributesJsonV310
     * @example single
     */
    relationship_status: string;

    /**
     * @type {boolean}
     * @memberof CustomerWithAttributesJsonV310
     * @example false
     */
    kyc_status: boolean;
}
