/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv310banksBANKIDcustomersCUSTOMERIDdataFaceImage } from './obpv310banks-bankidcustomers-customeriddata-face-image';
 /**
 * 
 *
 * @export
 * @interface CUSTOMERIDDataBody
 */
export interface CUSTOMERIDDataBody {

    /**
     * @type {Obpv310banksBANKIDcustomersCUSTOMERIDdataFaceImage}
     * @memberof CUSTOMERIDDataBody
     */
    face_image: Obpv310banksBANKIDcustomersCUSTOMERIDdataFaceImage;

    /**
     * @type {string}
     * @memberof CUSTOMERIDDataBody
     * @example single
     */
    relationship_status: string;

    /**
     * @type {number}
     * @memberof CUSTOMERIDDataBody
     * @example 1
     */
    dependants: number;

    /**
     * @type {string}
     * @memberof CUSTOMERIDDataBody
     * @example Master
     */
    highest_education_attained: string;

    /**
     * @type {string}
     * @memberof CUSTOMERIDDataBody
     * @example worker
     */
    employment_status: string;
}
