/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransactionBankAccountJson } from './transaction-bank-account-json';
import { TransactionRequestBankAccountJson } from './transaction-request-bank-account-json';
 /**
 * 
 *
 * @export
 * @interface DoubleEntryTransactionJson
 */
export interface DoubleEntryTransactionJson {

    /**
     * @type {TransactionRequestBankAccountJson}
     * @memberof DoubleEntryTransactionJson
     */
    transaction_request: TransactionRequestBankAccountJson;

    /**
     * @type {TransactionBankAccountJson}
     * @memberof DoubleEntryTransactionJson
     */
    debit_transaction: TransactionBankAccountJson;

    /**
     * @type {TransactionBankAccountJson}
     * @memberof DoubleEntryTransactionJson
     */
    credit_transaction: TransactionBankAccountJson;
}
