/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ErrorFilterSortDirectionError
 */
export interface ErrorFilterSortDirectionError {

    /**
     * @type {string}
     * @memberof ErrorFilterSortDirectionError
     * @example OBP-10023: obp_sort_direction parameter can only take two values: DESC or ASC!
     */
    message?: string;
}
