/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20092List } from './inline-response20092-list';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20092
 */
export interface InlineResponse20092 {

    /**
     * @type {Array<InlineResponse20092List>}
     * @memberof InlineResponse20092
     */
    list: Array<InlineResponse20092List>;
}
