/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomersMobilephonenumberBody } from './customers-mobilephonenumber-body';
import { InlineResponse201DetailsToTransferToPhoneFrom } from './inline-response201-details-to-transfer-to-phone-from';
import { Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue } from './obpv210banks-bankidaccounts-accountidviewidtransactionrequesttypes-sandboxtantransactionrequests-value';
 /**
 * 
 *
 * @export
 * @interface InlineResponse201DetailsToTransferToPhone
 */
export interface InlineResponse201DetailsToTransferToPhone {

    /**
     * @type {Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue}
     * @memberof InlineResponse201DetailsToTransferToPhone
     */
    value: Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue;

    /**
     * @type {string}
     * @memberof InlineResponse201DetailsToTransferToPhone
     * @example String
     */
    description: string;

    /**
     * @type {string}
     * @memberof InlineResponse201DetailsToTransferToPhone
     * @example String
     */
    message: string;

    /**
     * @type {InlineResponse201DetailsToTransferToPhoneFrom}
     * @memberof InlineResponse201DetailsToTransferToPhone
     */
    from: InlineResponse201DetailsToTransferToPhoneFrom;

    /**
     * @type {CustomersMobilephonenumberBody}
     * @memberof InlineResponse201DetailsToTransferToPhone
     */
    to: CustomersMobilephonenumberBody;
}
