/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv500banksBANKIDproductsPRODUCTCODEMeta } from './obpv500banks-bankidproducts-productcodemeta';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20037ParentProductParentProduct
 */
export interface InlineResponse20037ParentProductParentProduct {

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example testBank2
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example GRANDPARENT_CODE
     */
    code: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example product name
     */
    name: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example category
     */
    category: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example family
     */
    family: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example super family
     */
    super_family: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example www.example.com/prod1/more-info.html
     */
    more_info_url: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example Details
     */
    details: string;

    /**
     * @type {string}
     * @memberof InlineResponse20037ParentProductParentProduct
     * @example Description
     */
    description: string;

    /**
     * @type {Obpv500banksBANKIDproductsPRODUCTCODEMeta}
     * @memberof InlineResponse20037ParentProductParentProduct
     */
    meta: Obpv500banksBANKIDproductsPRODUCTCODEMeta;
}
