/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20018UserEntitlements } from './inline-response20018-user-entitlements';
import { InlineResponse20020Views } from './inline-response20020-views';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20020
 */
export interface InlineResponse20020 {

    /**
     * @type {string}
     * @memberof InlineResponse20020
     * @example 9ca9a7e4-6d02-40e3-a129-0b2bf89de9b1
     */
    user_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20020
     * @example felixsmith@example.com
     */
    email: string;

    /**
     * @type {string}
     * @memberof InlineResponse20020
     * @example Chris
     */
    provider_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20020
     * @example http://127.0.0.1:8080
     */
    provider: string;

    /**
     * @type {string}
     * @memberof InlineResponse20020
     * @example felixsmith
     */
    username: string;

    /**
     * @type {InlineResponse20018UserEntitlements}
     * @memberof InlineResponse20020
     */
    entitlements: InlineResponse20018UserEntitlements;

    /**
     * @type {InlineResponse20020Views}
     * @memberof InlineResponse20020
     */
    views: InlineResponse20020Views;
}
