/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2006DependentEndpoints
 */
export interface InlineResponse2006DependentEndpoints {

    /**
     * @type {string}
     * @memberof InlineResponse2006DependentEndpoints
     * @example getAccounts
     */
    name: string;

    /**
     * @type {string}
     * @memberof InlineResponse2006DependentEndpoints
     * @example OBPv3.0.0
     */
    version: string;
}
