/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2001BankId } from './inline-response2001-bank-id';
import { InlineResponse201DetailsValue } from './inline-response201-details-value';
import { Obpv210banksBANKIDtransactiontypesId } from './obpv210banks-bankidtransactiontypes-id';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {

    /**
     * @type {Obpv210banksBANKIDtransactiontypesId}
     * @memberof InlineResponse2001
     */
    id: Obpv210banksBANKIDtransactiontypesId;

    /**
     * @type {InlineResponse2001BankId}
     * @memberof InlineResponse2001
     */
    bankId: InlineResponse2001BankId;

    /**
     * @type {string}
     * @memberof InlineResponse2001
     * @example 80080
     */
    shortCode: string;

    /**
     * @type {string}
     * @memberof InlineResponse2001
     * @example SANDBOX_TAN
     */
    summary: string;

    /**
     * @type {string}
     * @memberof InlineResponse2001
     * @example This is the sandbox mode, charging litter money.
     */
    description: string;

    /**
     * @type {InlineResponse201DetailsValue}
     * @memberof InlineResponse2001
     */
    charge: InlineResponse201DetailsValue;
}
