/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20045AccountViewsAvailable } from './inline-response20045-account-views-available';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20045Account
 */
export interface InlineResponse20045Account {

    /**
     * @type {string}
     * @memberof InlineResponse20045Account
     * @example 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0
     */
    id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20045Account
     * @example My Account
     */
    label: string;

    /**
     * @type {Array<InlineResponse20045AccountViewsAvailable>}
     * @memberof InlineResponse20045Account
     */
    views_available: Array<InlineResponse20045AccountViewsAvailable>;

    /**
     * @type {string}
     * @memberof InlineResponse20045Account
     * @example gh.29.uk
     */
    bank_id: string;
}
