/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20059Attributes } from './inline-response20059-attributes';
import { InlineResponse20122Challenges } from './inline-response20122-challenges';
import { InlineResponse201Charge } from './inline-response201-charge';
import { InlineResponse201Details } from './inline-response201-details';
import { Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsTo } from './obpv210banks-bankidaccounts-accountidviewidtransactionrequesttypes-sandboxtantransactionrequests-to';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20122
 */
export interface InlineResponse20122 {

    /**
     * @type {string}
     * @memberof InlineResponse20122
     * @example 4050046c-63b3-4868-8a22-14b4181d33a6
     */
    id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20122
     * @example SANDBOX_TAN
     */
    type: string;

    /**
     * @type {Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsTo}
     * @memberof InlineResponse20122
     */
    from: Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsTo;

    /**
     * @type {InlineResponse201Details}
     * @memberof InlineResponse20122
     */
    details: InlineResponse201Details;

    /**
     * @type {Array<string>}
     * @memberof InlineResponse20122
     */
    transaction_ids: Array<string>;

    /**
     * @type {string}
     * @memberof InlineResponse20122
     * @example COMPLETED
     */
    status: string;

    /**
     * @type {string}
     * @memberof InlineResponse20122
     * @example 1100-01-01T00:00:00Z
     */
    start_date: string;

    /**
     * @type {string}
     * @memberof InlineResponse20122
     * @example 1100-01-01T00:00:00Z
     */
    end_date: string;

    /**
     * @type {Array<InlineResponse20122Challenges>}
     * @memberof InlineResponse20122
     */
    challenges: Array<InlineResponse20122Challenges>;

    /**
     * @type {InlineResponse201Charge}
     * @memberof InlineResponse20122
     */
    charge: InlineResponse201Charge;

    /**
     * @type {Array<InlineResponse20059Attributes>}
     * @memberof InlineResponse20122
     */
    attributes: Array<InlineResponse20059Attributes>;
}
