/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20059Banks } from './inline-response20059-banks';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20059
 */
export interface InlineResponse20059 {

    /**
     * @type {Array<InlineResponse20059Banks>}
     * @memberof InlineResponse20059
     */
    banks: Array<InlineResponse20059Banks>;
}
