/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20054
 */
export interface InlineResponse20054 {

    /**
     * @type {boolean}
     * @memberof InlineResponse20054
     * @example true
     */
    enabled: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse20054
     * @example REDIS
     */
    technology: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20054
     * @example true
     */
    service_available: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse20054
     * @example true
     */
    is_active: boolean;
}
