/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20033Keys } from './inline-response20033-keys';
import { InlineResponse20033Present } from './inline-response20033-present';
import { Obpv310banksBANKIDmeetingsCreator } from './obpv310banks-bankidmeetings-creator';
import { Obpv310banksBANKIDmeetingsInvitees } from './obpv310banks-bankidmeetings-invitees';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20110
 */
export interface InlineResponse20110 {

    /**
     * @type {string}
     * @memberof InlineResponse20110
     * @example UUID-String
     */
    meeting_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20110
     * @example Chris
     */
    provider_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20110
     * @example String, eg: onboarding
     */
    purpose_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20110
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {InlineResponse20033Present}
     * @memberof InlineResponse20110
     */
    present: InlineResponse20033Present;

    /**
     * @type {InlineResponse20033Keys}
     * @memberof InlineResponse20110
     */
    keys: InlineResponse20033Keys;

    /**
     * @type {string}
     * @memberof InlineResponse20110
     * @example 1100-01-01T00:00:00Z
     */
    when: string;

    /**
     * @type {Obpv310banksBANKIDmeetingsCreator}
     * @memberof InlineResponse20110
     */
    creator: Obpv310banksBANKIDmeetingsCreator;

    /**
     * @type {Array<Obpv310banksBANKIDmeetingsInvitees>}
     * @memberof InlineResponse20110
     */
    invitees: Array<Obpv310banksBANKIDmeetingsInvitees>;
}
