/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20036ProductCollection } from './inline-response20036-product-collection';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20036
 */
export interface InlineResponse20036 {

    /**
     * @type {Array<InlineResponse20036ProductCollection>}
     * @memberof InlineResponse20036
     */
    product_collection: Array<InlineResponse20036ProductCollection>;
}
