/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200157
 */
export interface InlineResponse200157 {

    /**
     * @type {string}
     * @memberof InlineResponse200157
     * @example felixsmith
     */
    username: string;

    /**
     * @type {number}
     * @memberof InlineResponse200157
     * @example 0
     */
    bad_attempts_since_last_success_or_reset: number;

    /**
     * @type {string}
     * @memberof InlineResponse200157
     * @example 1100-01-01T01:01:01Z
     */
    last_failure_date: string;
}
