/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20116DetailsAttributes } from './inline-response20116-details-attributes';
import { InlineResponse20116DetailsBankRoutings } from './inline-response20116-details-bank-routings';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20116Details
 */
export interface InlineResponse20116Details {

    /**
     * @type {Array<InlineResponse20116DetailsBankRoutings>}
     * @memberof InlineResponse20116Details
     */
    bank_routings: Array<InlineResponse20116DetailsBankRoutings>;

    /**
     * @type {string}
     * @memberof InlineResponse20116Details
     * @example Societe Generale
     */
    bank: string;

    /**
     * @type {string}
     * @memberof InlineResponse20116Details
     */
    branch: string;

    /**
     * @type {string}
     * @memberof InlineResponse20116Details
     * @example Neue mainzer strasse 46-50
     */
    address: string;

    /**
     * @type {string}
     * @memberof InlineResponse20116Details
     * @example Frankfurt am Main
     */
    city: string;

    /**
     * @type {string}
     * @memberof InlineResponse20116Details
     * @example 60311
     */
    postcode: string;

    /**
     * @type {string}
     * @memberof InlineResponse20116Details
     */
    phone: string;

    /**
     * @type {string}
     * @memberof InlineResponse20116Details
     * @example Germany
     */
    country: string;

    /**
     * @type {Array<InlineResponse20116DetailsAttributes>}
     * @memberof InlineResponse20116Details
     */
    attributes: Array<InlineResponse20116DetailsAttributes>;
}
