/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20148AccountAttributes } from './inline-response20148-account-attributes';
import { InlineResponse20149Contracts } from './inline-response20149-contracts';
import { Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue } from './obpv210banks-bankidaccounts-accountidviewidtransactionrequesttypes-sandboxtantransactionrequests-value';
import { Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings } from './obpv310managementbanks-bankidaccounts-accountidaccount-routings';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20149Accounts
 */
export interface InlineResponse20149Accounts {

    /**
     * @type {string}
     * @memberof InlineResponse20149Accounts
     * @example 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0
     */
    account_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20149Accounts
     * @example My Account
     */
    label: string;

    /**
     * @type {string}
     * @memberof InlineResponse20149Accounts
     * @example 787LOW
     */
    product_code: string;

    /**
     * @type {Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue}
     * @memberof InlineResponse20149Accounts
     */
    balance: Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue;

    /**
     * @type {string}
     * @memberof InlineResponse20149Accounts
     * @example DERBY6
     */
    branch_id: string;

    /**
     * @type {Array<InlineResponse20149Contracts>}
     * @memberof InlineResponse20149Accounts
     */
    contracts: Array<InlineResponse20149Contracts>;

    /**
     * @type {Array<Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings>}
     * @memberof InlineResponse20149Accounts
     */
    account_routings: Array<Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings>;

    /**
     * @type {Array<InlineResponse20148AccountAttributes>}
     * @memberof InlineResponse20149Accounts
     */
    account_attributes: Array<InlineResponse20148AccountAttributes>;
}
