/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200126BackendMessages
 */
export interface InlineResponse200126BackendMessages {

    /**
     * @type {string}
     * @memberof InlineResponse200126BackendMessages
     */
    source: string;

    /**
     * @type {string}
     * @memberof InlineResponse200126BackendMessages
     */
    status: string;

    /**
     * @type {string}
     * @memberof InlineResponse200126BackendMessages
     */
    errorCode: string;

    /**
     * @type {string}
     * @memberof InlineResponse200126BackendMessages
     */
    text: string;

    /**
     * @type {string}
     * @memberof InlineResponse200126BackendMessages
     * @example 5.123
     */
    duration: string;
}
