/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20039AkkaPorts } from './inline-response20039-akka-ports';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20039Akka
 */
export interface InlineResponse20039Akka {

    /**
     * @type {Array<InlineResponse20039AkkaPorts>}
     * @memberof InlineResponse20039Akka
     */
    ports: Array<InlineResponse20039AkkaPorts>;

    /**
     * @type {string}
     * @memberof InlineResponse20039Akka
     * @example Debug
     */
    log_level: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20039Akka
     * @example true
     */
    remote_data_secret_matched: boolean;
}
