/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv400managementbanksBANKIDendpointmappingsENDPOINTMAPPINGIDResponseMapping } from './obpv400managementbanks-bankidendpointmappings-endpointmappingidresponse-mapping';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2008Endpointmappings
 */
export interface InlineResponse2008Endpointmappings {

    /**
     * @type {string}
     * @memberof InlineResponse2008Endpointmappings
     * @example OBPv4.0.0-dynamicEndpoint_POST_account
     */
    operation_id: string;

    /**
     * @type {any}
     * @memberof InlineResponse2008Endpointmappings
     */
    request_mapping: any;

    /**
     * @type {Obpv400managementbanksBANKIDendpointmappingsENDPOINTMAPPINGIDResponseMapping}
     * @memberof InlineResponse2008Endpointmappings
     */
    response_mapping: Obpv400managementbanksBANKIDendpointmappingsENDPOINTMAPPINGIDResponseMapping;

    /**
     * @type {string}
     * @memberof InlineResponse2008Endpointmappings
     * @example b4e0352a-9a0f-4bfa-b30b-9003aa467f50
     */
    endpoint_mapping_id: string;
}
