/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200149Metrics } from './inline-response200149-metrics';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200149
 */
export interface InlineResponse200149 {

    /**
     * @type {Array<InlineResponse200149Metrics>}
     * @memberof InlineResponse200149
     */
    metrics: Array<InlineResponse200149Metrics>;
}
