/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20017AccountRules } from './inline-response20017-account-rules';
import { InlineResponse2009MetadataCorporateLocationUser } from './inline-response2009-metadata-corporate-location-user';
import { InlineResponse2016 } from './inline-response2016';
import { Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue } from './obpv210banks-bankidaccounts-accountidviewidtransactionrequesttypes-sandboxtantransactionrequests-value';
import { Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings } from './obpv310managementbanks-bankidaccounts-accountidaccount-routings';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20017
 */
export interface InlineResponse20017 {

    /**
     * @type {string}
     * @memberof InlineResponse20017
     * @example 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0
     */
    id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20017
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20017
     * @example My Account
     */
    label: string;

    /**
     * @type {string}
     * @memberof InlineResponse20017
     */
    number: string;

    /**
     * @type {Array<InlineResponse2009MetadataCorporateLocationUser>}
     * @memberof InlineResponse20017
     */
    owners: Array<InlineResponse2009MetadataCorporateLocationUser>;

    /**
     * @type {string}
     * @memberof InlineResponse20017
     */
    type: string;

    /**
     * @type {Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue}
     * @memberof InlineResponse20017
     */
    balance: Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue;

    /**
     * @type {Array<Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings>}
     * @memberof InlineResponse20017
     */
    account_routings: Array<Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings>;

    /**
     * @type {Array<InlineResponse20017AccountRules>}
     * @memberof InlineResponse20017
     */
    account_rules: Array<InlineResponse20017AccountRules>;

    /**
     * @type {Array<InlineResponse2016>}
     * @memberof InlineResponse20017
     */
    account_attributes: Array<InlineResponse2016>;
}
