/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200136TransactionRequestsWithCharges } from './inline-response200136-transaction-requests-with-charges';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200136
 */
export interface InlineResponse200136 {

    /**
     * @type {Array<InlineResponse200136TransactionRequestsWithCharges>}
     * @memberof InlineResponse200136
     */
    transaction_requests_with_charges: Array<InlineResponse200136TransactionRequestsWithCharges>;
}
