/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2006MessageDocs } from './inline-response2006-message-docs';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {

    /**
     * @type {Array<InlineResponse2006MessageDocs>}
     * @memberof InlineResponse2006
     */
    message_docs: Array<InlineResponse2006MessageDocs>;
}
