/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2009Holder } from './inline-response2009-holder';
import { Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings } from './obpv310managementbanks-bankidaccounts-accountidaccount-routings';
import { Obpv500banksBankRoutings } from './obpv500banks-bank-routings';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20019OtherAccount
 */
export interface InlineResponse20019OtherAccount {

    /**
     * @type {string}
     * @memberof InlineResponse20019OtherAccount
     * @example 5995d6a2-01b3-423c-a173-5481df49bdaf
     */
    id: string;

    /**
     * @type {InlineResponse2009Holder}
     * @memberof InlineResponse20019OtherAccount
     */
    holder: InlineResponse2009Holder;

    /**
     * @type {Obpv500banksBankRoutings}
     * @memberof InlineResponse20019OtherAccount
     */
    bank_routing: Obpv500banksBankRoutings;

    /**
     * @type {Array<Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings>}
     * @memberof InlineResponse20019OtherAccount
     */
    account_routings: Array<Obpv310managementbanksBANKIDaccountsACCOUNTIDAccountRoutings>;
}
