/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse201DetailsToSepaCreditTransfersCreditorAccount } from './inline-response201-details-to-sepa-credit-transfers-creditor-account';
import { InlineResponse201DetailsToSepaCreditTransfersDebtorAccount } from './inline-response201-details-to-sepa-credit-transfers-debtor-account';
import { Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue } from './obpv210banks-bankidaccounts-accountidviewidtransactionrequesttypes-sandboxtantransactionrequests-value';
 /**
 * 
 *
 * @export
 * @interface InlineResponse201DetailsToSepaCreditTransfers
 */
export interface InlineResponse201DetailsToSepaCreditTransfers {

    /**
     * @type {InlineResponse201DetailsToSepaCreditTransfersDebtorAccount}
     * @memberof InlineResponse201DetailsToSepaCreditTransfers
     */
    debtorAccount: InlineResponse201DetailsToSepaCreditTransfersDebtorAccount;

    /**
     * @type {Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue}
     * @memberof InlineResponse201DetailsToSepaCreditTransfers
     */
    instructedAmount: Obpv210banksBANKIDaccountsACCOUNTIDVIEWIDtransactionrequesttypesSANDBOXTANtransactionrequestsValue;

    /**
     * @type {InlineResponse201DetailsToSepaCreditTransfersCreditorAccount}
     * @memberof InlineResponse201DetailsToSepaCreditTransfers
     */
    creditorAccount: InlineResponse201DetailsToSepaCreditTransfersCreditorAccount;

    /**
     * @type {string}
     * @memberof InlineResponse201DetailsToSepaCreditTransfers
     * @example John Miles
     */
    creditorName: string;
}
