/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20157
 */
export interface InlineResponse20157 {

    /**
     * @type {string}
     * @memberof InlineResponse20157
     * @example 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh
     */
    agent_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20157
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20157
     * @example Eveline Tripman
     */
    legal_name: string;

    /**
     * @type {string}
     * @memberof InlineResponse20157
     * @example +49 30 901820
     */
    mobile_phone_number: string;

    /**
     * @type {string}
     * @memberof InlineResponse20157
     * @example 5987953
     */
    agent_number: string;

    /**
     * @type {string}
     * @memberof InlineResponse20157
     * @example EUR
     */
    currency: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20157
     * @example false
     */
    is_confirmed_agent: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse20157
     * @example true
     */
    is_pending_agent: boolean;
}
