/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20025Cards } from './inline-response20025-cards';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20025
 */
export interface InlineResponse20025 {

    /**
     * @type {Array<InlineResponse20025Cards>}
     * @memberof InlineResponse20025
     */
    cards: Array<InlineResponse20025Cards>;
}
