/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20035ProductAttributes } from './inline-response20035-product-attributes';
import { Obpv500banksBANKIDproductsPRODUCTCODEMeta } from './obpv500banks-bankidproducts-productcodemeta';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20035Products
 */
export interface InlineResponse20035Products {

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example 1234BW
     */
    code: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example parent
     */
    parent_product_code: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example product name
     */
    name: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example category
     */
    category: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example family
     */
    family: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example super family
     */
    super_family: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example www.example.com/prod1/more-info.html
     */
    more_info_url: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example Details
     */
    details: string;

    /**
     * @type {string}
     * @memberof InlineResponse20035Products
     * @example Description
     */
    description: string;

    /**
     * @type {Obpv500banksBANKIDproductsPRODUCTCODEMeta}
     * @memberof InlineResponse20035Products
     */
    meta: Obpv500banksBANKIDproductsPRODUCTCODEMeta;

    /**
     * @type {Array<InlineResponse20035ProductAttributes>}
     * @memberof InlineResponse20035Products
     */
    product_attributes: Array<InlineResponse20035ProductAttributes>;
}
