/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface KycDocumentJSON
 */
export interface KycDocumentJSON {

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     * @example PlaceholderString
     */
    number: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     * @example 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh
     */
    customer_id: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     * @example 5987953
     */
    customer_number: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     */
    issue_date: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     * @example PlaceholderString
     */
    id: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     * @example PlaceholderString
     */
    type: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     * @example PlaceholderString
     */
    issue_place: string;

    /**
     * @type {string}
     * @memberof KycDocumentJSON
     */
    expiry_date: string;
}
