/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OpeningTimesV300 } from './opening-times-v300';
 /**
 * 
 *
 * @export
 * @interface LobbyJsonV330
 */
export interface LobbyJsonV330 {

    /**
     * @type {Array<OpeningTimesV300>}
     * @memberof LobbyJsonV330
     */
    sunday: Array<OpeningTimesV300>;

    /**
     * @type {Array<OpeningTimesV300>}
     * @memberof LobbyJsonV330
     */
    tuesday: Array<OpeningTimesV300>;

    /**
     * @type {Array<OpeningTimesV300>}
     * @memberof LobbyJsonV330
     */
    wednesday: Array<OpeningTimesV300>;

    /**
     * @type {Array<OpeningTimesV300>}
     * @memberof LobbyJsonV330
     */
    monday: Array<OpeningTimesV300>;

    /**
     * @type {Array<OpeningTimesV300>}
     * @memberof LobbyJsonV330
     */
    friday: Array<OpeningTimesV300>;

    /**
     * @type {Array<OpeningTimesV300>}
     * @memberof LobbyJsonV330
     */
    thursday: Array<OpeningTimesV300>;

    /**
     * @type {Array<OpeningTimesV300>}
     * @memberof LobbyJsonV330
     */
    saturday: Array<OpeningTimesV300>;
}
