/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountAttributeResponseJson } from './account-attribute-response-json';
import { AccountRoutingJsonV121 } from './account-routing-json-v121';
import { AccountRuleJsonV300 } from './account-rule-json-v300';
import { AmountOfMoneyJsonV121 } from './amount-of-money-json-v121';
import { UserJSONV121 } from './user-jsonv121';
 /**
 * 
 *
 * @export
 * @interface ModeratedFirehoseAccountJsonV400
 */
export interface ModeratedFirehoseAccountJsonV400 {

    /**
     * @type {string}
     * @memberof ModeratedFirehoseAccountJsonV400
     */
    number: string;

    /**
     * @type {Array<AccountAttributeResponseJson>}
     * @memberof ModeratedFirehoseAccountJsonV400
     */
    account_attributes?: Array<AccountAttributeResponseJson>;

    /**
     * @type {Array<AccountRoutingJsonV121>}
     * @memberof ModeratedFirehoseAccountJsonV400
     */
    account_routings: Array<AccountRoutingJsonV121>;

    /**
     * @type {string}
     * @memberof ModeratedFirehoseAccountJsonV400
     * @example My Account
     */
    label: string;

    /**
     * @type {Array<UserJSONV121>}
     * @memberof ModeratedFirehoseAccountJsonV400
     */
    owners: Array<UserJSONV121>;

    /**
     * @type {AmountOfMoneyJsonV121}
     * @memberof ModeratedFirehoseAccountJsonV400
     */
    balance: AmountOfMoneyJsonV121;

    /**
     * @type {string}
     * @memberof ModeratedFirehoseAccountJsonV400
     * @example 1234BW
     */
    product_code: string;

    /**
     * @type {string}
     * @memberof ModeratedFirehoseAccountJsonV400
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof ModeratedFirehoseAccountJsonV400
     * @example 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0
     */
    id: string;

    /**
     * @type {Array<AccountRuleJsonV300>}
     * @memberof ModeratedFirehoseAccountJsonV400
     */
    account_rules: Array<AccountRuleJsonV300>;
}
