/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv210sandboxdataimportMeta1 } from './obpv210sandboxdataimport-meta1';
 /**
 * 
 *
 * @export
 * @interface Obpv210sandboxdataimportProducts
 */
export interface Obpv210sandboxdataimportProducts {

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportProducts
     * @example bank1
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportProducts
     * @example prd1
     */
    code: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportProducts
     * @example product 1
     */
    name: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportProducts
     * @example cat1
     */
    category: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportProducts
     * @example fam1
     */
    family: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportProducts
     * @example sup fam 1
     */
    super_family: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportProducts
     * @example www.example.com/index1
     */
    more_info_url: string;

    /**
     * @type {Obpv210sandboxdataimportMeta1}
     * @memberof Obpv210sandboxdataimportProducts
     */
    meta: Obpv210sandboxdataimportMeta1;
}
