/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv210sandboxdataimportAddress } from './obpv210sandboxdataimport-address';
import { Obpv210sandboxdataimportDriveUp } from './obpv210sandboxdataimport-drive-up';
import { Obpv210sandboxdataimportLobby } from './obpv210sandboxdataimport-lobby';
import { Obpv210sandboxdataimportLocation } from './obpv210sandboxdataimport-location';
import { Obpv210sandboxdataimportMeta } from './obpv210sandboxdataimport-meta';
 /**
 * 
 *
 * @export
 * @interface Obpv210sandboxdataimportBranches
 */
export interface Obpv210sandboxdataimportBranches {

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportBranches
     * @example branch1
     */
    id: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportBranches
     * @example bank1
     */
    bank_id: string;

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportBranches
     * @example Genel Müdürlük
     */
    name: string;

    /**
     * @type {Obpv210sandboxdataimportAddress}
     * @memberof Obpv210sandboxdataimportBranches
     */
    address: Obpv210sandboxdataimportAddress;

    /**
     * @type {Obpv210sandboxdataimportLocation}
     * @memberof Obpv210sandboxdataimportBranches
     */
    location: Obpv210sandboxdataimportLocation;

    /**
     * @type {Obpv210sandboxdataimportMeta}
     * @memberof Obpv210sandboxdataimportBranches
     */
    meta: Obpv210sandboxdataimportMeta;

    /**
     * @type {Obpv210sandboxdataimportLobby}
     * @memberof Obpv210sandboxdataimportBranches
     */
    lobby: Obpv210sandboxdataimportLobby;

    /**
     * @type {Obpv210sandboxdataimportDriveUp}
     * @memberof Obpv210sandboxdataimportBranches
     */
    driveUp: Obpv210sandboxdataimportDriveUp;
}
