/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv210sandboxdataimportDetails } from './obpv210sandboxdataimport-details';
import { Obpv210sandboxdataimportThisAccount } from './obpv210sandboxdataimport-this-account';
 /**
 * 
 *
 * @export
 * @interface Obpv210sandboxdataimportTransactions
 */
export interface Obpv210sandboxdataimportTransactions {

    /**
     * @type {string}
     * @memberof Obpv210sandboxdataimportTransactions
     * @example transaction-without-counterparty
     */
    id: string;

    /**
     * @type {Obpv210sandboxdataimportThisAccount}
     * @memberof Obpv210sandboxdataimportTransactions
     */
    this_account: Obpv210sandboxdataimportThisAccount;

    /**
     * @type {Obpv210sandboxdataimportDetails}
     * @memberof Obpv210sandboxdataimportTransactions
     */
    details: Obpv210sandboxdataimportDetails;
}
