/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv400managementbanksBANKIDdynamicentitiesDYNAMICENTITYIDFooBarProperties } from './obpv400managementbanks-bankiddynamicentities-dynamicentityidfoo-bar-properties';
 /**
 * 
 *
 * @export
 * @interface Obpv400managementsystemdynamicentitiesFooBar
 */
export interface Obpv400managementsystemdynamicentitiesFooBar {

    /**
     * @type {string}
     * @memberof Obpv400managementsystemdynamicentitiesFooBar
     * @example description of this entity, can be markdown text.
     */
    description: string;

    /**
     * @type {Array<string>}
     * @memberof Obpv400managementsystemdynamicentitiesFooBar
     */
    required: Array<string>;

    /**
     * @type {Obpv400managementbanksBANKIDdynamicentitiesDYNAMICENTITYIDFooBarProperties}
     * @memberof Obpv400managementsystemdynamicentitiesFooBar
     */
    properties: Obpv400managementbanksBANKIDdynamicentitiesDYNAMICENTITYIDFooBarProperties;
}
