/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MetaJsonV140 } from './meta-json-v140';
import { ProductAttributeResponseWithoutBankIdJson } from './product-attribute-response-without-bank-id-json';
import { ProductFeeJsonV400 } from './product-fee-json-v400';
 /**
 * 
 *
 * @export
 * @interface ProductJsonV400
 */
export interface ProductJsonV400 {

    /**
     * @type {string}
     * @memberof ProductJsonV400
     * @example Deposit Account 1
     */
    name: string;

    /**
     * @type {string}
     * @memberof ProductJsonV400
     * @example Description of the object. Maximum length is 2000. It can be any characters here.
     */
    description: string;

    /**
     * @type {string}
     * @memberof ProductJsonV400
     * @example www.example.com/xyz
     */
    terms_and_conditions_url: string;

    /**
     * @type {string}
     * @memberof ProductJsonV400
     * @example www.example.com/abc
     */
    more_info_url: string;

    /**
     * @type {Array<ProductAttributeResponseWithoutBankIdJson>}
     * @memberof ProductJsonV400
     */
    attributes?: Array<ProductAttributeResponseWithoutBankIdJson>;

    /**
     * @type {string}
     * @memberof ProductJsonV400
     * @example 1234BW
     */
    product_code: string;

    /**
     * @type {string}
     * @memberof ProductJsonV400
     * @example gh.29.uk
     */
    bank_id: string;

    /**
     * @type {MetaJsonV140}
     * @memberof ProductJsonV400
     */
    meta: MetaJsonV140;

    /**
     * @type {Array<ProductFeeJsonV400>}
     * @memberof ProductJsonV400
     */
    fees?: Array<ProductFeeJsonV400>;

    /**
     * @type {string}
     * @memberof ProductJsonV400
     * @example 787LOW
     */
    parent_product_code: string;
}
