/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductFeeResponseJsonV400 } from './product-fee-response-json-v400';
 /**
 * 
 *
 * @export
 * @interface ProductFeesResponseJsonV400
 */
export interface ProductFeesResponseJsonV400 {

    /**
     * @type {Array<ProductFeeResponseJsonV400>}
     * @memberof ProductFeesResponseJsonV400
     */
    product_fees: Array<ProductFeeResponseJsonV400>;
}
