/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductFeeValueJsonV400 } from './product-fee-value-json-v400';
 /**
 * 
 *
 * @export
 * @interface ProductFeeJsonV400
 */
export interface ProductFeeJsonV400 {

    /**
     * @type {string}
     * @memberof ProductFeeJsonV400
     * @example ACCOUNT_MANAGEMENT_FEE
     */
    name: string;

    /**
     * @type {boolean}
     * @memberof ProductFeeJsonV400
     * @example true
     */
    is_active: boolean;

    /**
     * @type {string}
     * @memberof ProductFeeJsonV400
     * @example More information about this fee
     */
    more_info: string;

    /**
     * @type {string}
     * @memberof ProductFeeJsonV400
     * @example 696hlAHLFKUHE37469287634
     */
    product_fee_id?: string;

    /**
     * @type {ProductFeeValueJsonV400}
     * @memberof ProductFeeJsonV400
     */
    value: ProductFeeValueJsonV400;
}
