/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JsonDynamicResourceDocExampleRequestBody } from './json-dynamic-resource-doc-example-request-body';
import { JsonDynamicResourceDocSuccessResponseBody } from './json-dynamic-resource-doc-success-response-body';
 /**
 * 
 *
 * @export
 * @interface ResourceDocFragment
 */
export interface ResourceDocFragment {

    /**
     * @type {string}
     * @memberof ResourceDocFragment
     * @example POST
     */
    request_verb: string;

    /**
     * @type {string}
     * @memberof ResourceDocFragment
     * @example /my_user/MY_USER_ID
     */
    request_url: string;

    /**
     * @type {JsonDynamicResourceDocExampleRequestBody}
     * @memberof ResourceDocFragment
     */
    example_request_body?: JsonDynamicResourceDocExampleRequestBody;

    /**
     * @type {JsonDynamicResourceDocSuccessResponseBody}
     * @memberof ResourceDocFragment
     */
    success_response_body?: JsonDynamicResourceDocSuccessResponseBody;
}
