/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SandboxBankImport
 */
export interface SandboxBankImport {

    /**
     * @type {string}
     * @memberof SandboxBankImport
     * @example http://example.com/2
     */
    website: string;

    /**
     * @type {string}
     * @memberof SandboxBankImport
     * @example Bank 2 Inc.
     */
    full_name: string;

    /**
     * @type {string}
     * @memberof SandboxBankImport
     * @example http://example.com/logo2
     */
    logo: string;

    /**
     * @type {string}
     * @memberof SandboxBankImport
     * @example bank2
     */
    id: string;

    /**
     * @type {string}
     * @memberof SandboxBankImport
     * @example bank 2
     */
    short_name: string;
}
