/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountAttributeResponseJson } from './account-attribute-response-json';
import { AccountRoutingJsonV121 } from './account-routing-json-v121';
import { AmountOfMoneyJsonV121 } from './amount-of-money-json-v121';
 /**
 * 
 *
 * @export
 * @interface SettlementAccountJson
 */
export interface SettlementAccountJson {

    /**
     * @type {Array<AccountAttributeResponseJson>}
     * @memberof SettlementAccountJson
     */
    account_attributes: Array<AccountAttributeResponseJson>;

    /**
     * @type {string}
     * @memberof SettlementAccountJson
     * @example DERBY6
     */
    branch_id: string;

    /**
     * @type {Array<AccountRoutingJsonV121>}
     * @memberof SettlementAccountJson
     */
    account_routings: Array<AccountRoutingJsonV121>;

    /**
     * @type {string}
     * @memberof SettlementAccountJson
     * @example My Account
     */
    label: string;

    /**
     * @type {AmountOfMoneyJsonV121}
     * @memberof SettlementAccountJson
     */
    balance: AmountOfMoneyJsonV121;

    /**
     * @type {string}
     * @memberof SettlementAccountJson
     * @example SEPA
     */
    payment_system: string;

    /**
     * @type {string}
     * @memberof SettlementAccountJson
     * @example 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0
     */
    account_id: string;
}
