/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AmountOfMoneyJsonV121 } from './amount-of-money-json-v121';
import { CounterpartyIdJson } from './counterparty-id-json';
import { TransactionRequestAttributeJsonV400 } from './transaction-request-attribute-json-v400';
 /**
 * 
 *
 * @export
 * @interface TransactionRequestBodyCounterpartyJSON
 */
export interface TransactionRequestBodyCounterpartyJSON {

    /**
     * @type {string}
     * @memberof TransactionRequestBodyCounterpartyJSON
     * @example A description for the transaction to the counterparty
     */
    description: string;

    /**
     * @type {string}
     * @memberof TransactionRequestBodyCounterpartyJSON
     * @example 20200127
     */
    future_date?: string;

    /**
     * @type {Array<TransactionRequestAttributeJsonV400>}
     * @memberof TransactionRequestBodyCounterpartyJSON
     */
    attributes?: Array<TransactionRequestAttributeJsonV400>;

    /**
     * @type {CounterpartyIdJson}
     * @memberof TransactionRequestBodyCounterpartyJSON
     */
    to: CounterpartyIdJson;

    /**
     * @type {string}
     * @memberof TransactionRequestBodyCounterpartyJSON
     * @example SHARED
     */
    charge_policy: string;

    /**
     * @type {AmountOfMoneyJsonV121}
     * @memberof TransactionRequestBodyCounterpartyJSON
     */
    value: AmountOfMoneyJsonV121;
}
