/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv500banksBankRoutings } from './obpv500banks-bank-routings';
 /**
 * 
 *
 * @export
 * @interface V500BanksBody
 */
export interface V500BanksBody {

    /**
     * @type {string}
     * @memberof V500BanksBody
     * @example gh.29.uk
     */
    id: string;

    /**
     * @type {string}
     * @memberof V500BanksBody
     * @example CGHZ
     */
    bank_code: string;

    /**
     * @type {string}
     * @memberof V500BanksBody
     * @example full name string
     */
    full_name: string;

    /**
     * @type {string}
     * @memberof V500BanksBody
     * @example logo url
     */
    logo: string;

    /**
     * @type {string}
     * @memberof V500BanksBody
     * @example www.openbankproject.com
     */
    website: string;

    /**
     * @type {Array<Obpv500banksBankRoutings>}
     * @memberof V500BanksBody
     */
    bank_routings: Array<Obpv500banksBankRoutings>;
}
