/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2025. Licensed under the AGPL and commercial licences.
 *
 * OpenAPI spec version: v5.1.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Obpv510banksBANKIDaccountsACCOUNTIDviewsVIEWIDuseraccountaccessViews } from './obpv510banks-bankidaccounts-accountidviews-viewiduseraccountaccess-views';
 /**
 * 
 *
 * @export
 * @interface VIEWIDUseraccountaccessBody
 */
export interface VIEWIDUseraccountaccessBody {

    /**
     * @type {string}
     * @memberof VIEWIDUseraccountaccessBody
     * @example felixsmith
     */
    username: string;

    /**
     * @type {string}
     * @memberof VIEWIDUseraccountaccessBody
     * @example dauth.ETHEREUM
     */
    provider: string;

    /**
     * @type {Array<Obpv510banksBANKIDaccountsACCOUNTIDviewsVIEWIDuseraccountaccessViews>}
     * @memberof VIEWIDUseraccountaccessBody
     */
    views: Array<Obpv510banksBANKIDaccountsACCOUNTIDviewsVIEWIDuseraccountaccessViews>;
}
